name: Makefile CI

on:
  push:
    branches: [ "release-1.18.7" ]
  pull_request:
    branches: [ "release-1.18.7" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Bazelisk
      uses: bazelbuild/setup-bazelisk@v2.0.0
            
    - name: Install dependencies
      run: make build
